$page.setWebTaskConfig({
    fileDownload:{
        baidu:{
            url:'http://www.baidu.com',
            fn:'listDownload'
        },
        wangyi:{
            url:'http://news.163.com/rank/',
            fn:'listDownload'
        }
    }
})